export const SEARCH_URLS_BUCKET = 'newSearchURLs'
export const SELLERS_BUCKET = 'sellersByRegionId'
export const CATEGORY_TREE_ROOT_BUCKET = 'categoryTree'
export const CATEGORY_TREE_CHILDREN_BUCKET = 'categoryTreeChildren'
export const SPECIFICATION_BUCKET = 'specificationField'
export const LIST_SPECIFICATIONS_BY_CATEGORY_ID = 'specificationByCategoryId'
export const CATEGORY_TREE_ROOT_PATH = 'categoryTree.json'
export const FACETS_BUCKET = 'facets'
export const SPEC_FILTER = 'specificationFilter'
export const MAP_QUERY_KEY = 'map'
export const MAP_VALUES_SEP = ','
export const PATH_SEPARATOR = '/'
export const SPACE_REPLACER = '-'
export const FILTER_TITLE_SEP = '_'
export const CATEGORY_SEGMENT = 'c'
export const FULL_TEXT_SEGMENT = 'ft'

export const APP_NAME = 'vtex.search-resolver@1.x'
